USE SQL_CLASS;

CREATE TABLE SALESMAN_TABLE
(
SALAESMANID INT,
SALESMANNAME VARCHAR(50),
COMMISSION DECIMAL (10,2),
CITY VARCHAR(50),
AGE INT,
);

CREATE TABLE CUSTOMER_TABLE
(
SALESMANID INT,
CUSTOMERID INT,
CUSTOMERNAME VARCHAR(50),
PURCHASEAMOUNT INT,
);

CREATE TABLE ORDERS_TABLE
(
ORDERID INT,
CUSTOMERID INT,
SALESMANID INT,
ORDERDATE DATE,
AMOUNT DECIMAL(10,2),
);

SELECT * FROM SALESMAN_TABLE;

SELECT * FROM CUSTOMER_TABLE;

SELECT * FROM ORDERS_TABLE;

INSERT INTO SALESMAN_TABLE (SALAESMANID,SALESMANNAME,COMMISSION,CITY,AGE)
VALUES (101,'JOE',50,'CALIFORNIA',17);
INSERT INTO SALESMAN_TABLE (SALAESMANID,SALESMANNAME,COMMISSION,CITY,AGE)
VALUES (102,'SIMON',75,'TEXAS',25);
INSERT INTO SALESMAN_TABLE (SALAESMANID,SALESMANNAME,COMMISSION,CITY,AGE)
VALUES (103,'JESSIE',105,'FLORIDA',35);
INSERT INTO SALESMAN_TABLE (SALAESMANID,SALESMANNAME,COMMISSION,CITY,AGE)
VALUES (104,'DANNY',100,'TEXAS',22);
INSERT INTO SALESMAN_TABLE (SALAESMANID,SALESMANNAME,COMMISSION,CITY,AGE)
VALUES (105,'LIA',65,'NEW JERSEY',30);

SELECT * FROM SALESMAN_TABLE;

INSERT INTO CUSTOMER_TABLE (SALESMANID,CUSTOMERID,CUSTOMERNAME,PURCHASEAMOUNT)
VALUES (101,2345,'ANDREW',550);
INSERT INTO CUSTOMER_TABLE (SALESMANID,CUSTOMERID,CUSTOMERNAME,PURCHASEAMOUNT)
VALUES (103,1575,'LUCKY',4500);
INSERT INTO CUSTOMER_TABLE (SALESMANID,CUSTOMERID,CUSTOMERNAME,PURCHASEAMOUNT)
VALUES (104,2345,'ANDREW',4000);
INSERT INTO CUSTOMER_TABLE (SALESMANID,CUSTOMERID,CUSTOMERNAME,PURCHASEAMOUNT)
VALUES (107,3747,'REMONA',2700);
INSERT INTO CUSTOMER_TABLE (SALESMANID,CUSTOMERID,CUSTOMERNAME,PURCHASEAMOUNT)
VALUES (110,4004,'JULIA',4545);

SELECT * FROM CUSTOMER_TABLE;

INSERT INTO ORDERS_TABLE (ORDERID,CUSTOMERID,SALESMANID,ORDERDATE,AMOUNT)
VALUES (5001,2345,101,'2021-07-04',550);
INSERT INTO ORDERS_TABLE (ORDERID,CUSTOMERID,SALESMANID,ORDERDATE,AMOUNT)
VALUES (5003,1234,105,'2022-02-05',1500);

SELECT * FROM ORDERS_TABLE;

***************************************************************************************************

1. INSERT A NEW RECORD IN YOUR ORDERS TABLE:-

INSERT INTO ORDERS_TABLE (ORDERID,CUSTOMERID,SALESMANID,ORDERDATE,AMOUNT)
VALUES (5004,3747,107,'2021-02-15',2700); 

2. ADD PRIMARY KEY CONSTRAINT FOR SALESMANID COLUMN IN SALESMAN TABLE. ADD DEFAULT CONSTRAINT FOR CITY COLUMN IN SALESMAN 
   TABLE .ADD FOREIGN KEY CONSTRAINT FOR SALESMANID COLUMN IN CUSTOMER TABLE.ADD NOT NULL CONSTRAINT IN CUSTOMER _NAME
   COLUMN FOR THE CUSTOMER TABLE.

  
*  EXEC sp_rename 'SALESMAN_TABLE.SALAESMANID', 'SALESMANID', 'COLUMN';

*  ALTER TABLE SALESMAN_TABLE
   ALTER COLUMN SALESMANID INT NOT NULL;

*  ALTER TABLE SALESMAN_TABLE
   ADD CONSTRAINT PK_SALESMAN_TABLE PRIMARY KEY (SALESMANID);

**************************************************************************************
* ALTER TABLE SALESMAN_TABLE
  ADD CONSTRAINT DF_SALESMAN_CITY DEFAULT 'UNKONWN' FOR CITY;

**************************************************************************************
 
* DELETE FROM CUSTOMER_TABLE 
  WHERE SALESMANID NOT IN (SELECT SALESMANID FROM SALESMAN_TABLE);

* UPDATE CUSTOMER_TABLE
  SET SALESMANID = 105
  WHERE SALESMANID NOT IN (SELECT SALESMANID FROM SALESMAN_TABLE);

* ALTER TABLE CUSTOMER_TABLE
  ALTER COLUMN SALESMANID INT NULL;
  
* ALTER TABLE CUSTOMER_TABLE
  ADD CONSTRAINT FK_CUSTOMER_SALESMAN FOREIGN KEY (SALESMANID)
  REFERENCES SALESMAN_TABLE (SALESMANID);

*************************************************************************************
* ALTER TABLE CUSTOMER_TABLE
  ALTER COLUMN CUSTOMERNAME VARCHAR(50) NOT NULL;

3. FETCH THE DATA WHERE THE CUSTOMERS NAME IS ENDING WITH 'N' ALSO GET THE PURCHASE AMOUNT VALUE GREATER THAN	500.

   SELECT * FROM CUSTOMER_TABLE
   WHERE CUSTOMERNAME LIKE '%N'
   AND PURCHASEAMOUNT > 500;

4. USING SET OPERATORS,RETIREVE THE FIRST RESULT WITH UNIQUE SALESMANID VALUES  FROM TWO  TABLES,AND THE OTHER RESULT CONTAINING
   SALESMANID WITH DUPLICATES FROM TWO TABLES.

   SELECT SALESMANID FROM CUSTOMER_TABLE
   UNION 
   SELECT SALESMANID FROM ORDERS_TABLE;

   SELECT SALESMANID FROM CUSTOMER_TABLE
   UNION ALL 
   SELECT SALESMANID FROM ORDERS_TABLE;

5. DISPLAY THE BELOW COLOUMN WHICH HAS THE MATCHING DATA.
   ORDERDATE,SALESMAN NAME,CUSTOMER NAME,COMMISSION,AND CITY WHICH HAS THE RANGE OF PURCHASE AMOUNT BETWEEN 500 TO 1500.

   SELECT O.ORDERDATE,
          S.SALESMANNAME,
          C.CUSTOMERNAME,
          S.COMMISSION,
          S.CITY
   FROM ORDERS_TABLE O
   JOIN CUSTOMER_TABLE C
       ON O.CUSTOMERID = C. CUSTOMERID
   JOIN SALESMAN_TABLE S
       ON O.SALESMANID = C.SALESMANID
    WHERE C.PURCHASEAMOUNT BETWEEN 500 AND 1500;

6. USING RIGHT JOIN FETCH ALL THE RESULT FROM SALESMAN AND ORDERSTABLE.

   SELECT S. SALESMANID,
          S.SALESMANNAME,
          O.ORDERID,
          O.CUSTOMERID,
          O.ORDERID,
          O.AMOUNT
   FROM SALESMAN_TABLE S
   RIGHT JOIN ORDERS_TABLE O
     ON S.SALESMANID = O.SALESMANID;


 
